/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2014-01-28 13:49:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
 session.setAttribute("fichier", "C:\\Users\\Valeri\\workspace2\\XMLproject\\fileBIS.xml"); 
      out.write("\r\n");
      out.write("\t\t<!-- MAIN -->\r\n");
      out.write("\t\t<div id=\"main\">\t\r\n");
      out.write("\t\t\t<div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- slider holder -->\r\n");
      out.write("\t\t\t\t<div id=\"slider-holder\" class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- slider -->\r\n");
      out.write("\t\t\t        <div class=\"flexslider home-slider\">\r\n");
      out.write("\t\t\t\t\t  <ul class=\"slides\">\r\n");
      out.write("\t\t\t\t\t    <li>\r\n");
      out.write("\t\t\t\t\t      <img src=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/img/slides/01.jpg\" alt=\"alt text\" />\r\n");
      out.write("\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t    <li>\r\n");
      out.write("\t\t\t\t\t      <img src=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/img/slides/02.jpg\" alt=\"alt text\" />\r\n");
      out.write("\t\t\t\t\t      <!-- <p class=\"flex-caption\">Pellentesque habitant morbi  feugiat vitae.</p> -->\r\n");
      out.write("\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t    <li>\r\n");
      out.write("\t\t\t\t\t      <img src=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/img/slides/03.jpg\" alt=\"alt text\" />\r\n");
      out.write("\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t        \t<!-- ENDS slider -->\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t        \t<div class=\"home-slider-clearfix \"></div>\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t        \t");
if (session.getAttribute("user") == null){ 
      out.write("\r\n");
      out.write("\t\t        \t<!-- Headline -->\r\n");
      out.write("\t\t        \t<div id=\"headline\">\r\n");
      out.write("                    <h2>CONNEXION</h2><br/>\r\n");
      out.write("                    <p>\r\n");
      out.write("                    \t<form action=\"");
      out.print( request.getContextPath() );
      out.write("/user/connexion\" method=\"POST\">\r\n");
      out.write("                    \t\tLOGIN<br> \r\n");
      out.write("                    \t\t<input type=\"text\" style=\"width:80%\" name=\"username\"><br/><br/>\r\n");
      out.write("                    \r\n");
      out.write("                    \t\tPASSWORD<input type=\"password\" style=\"width:80%\" name=\"password\"><br>\r\n");
      out.write("                    \t\t<input type=\"submit\" value=\"Valider\">\r\n");
      out.write("                    \t\t\r\n");
      out.write("                    \t\tMot de passe oublie ? <a href=\"#\"> Cliquez ici</a>\r\n");
      out.write("                    \t</form> \r\n");
      out.write("                    </p>\r\n");
      out.write("                    <em id=\"corner\"></em><br>\r\n");
      out.write("                    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/inscription\" class=\"hover_pink\"><h2>INSCRIVEZ VOUS </h2></a> <!-- redirection vers page inscription -->\r\n");
      out.write("\t\t        \t</div>\r\n");
      out.write("\t\t        \t<!-- ENDS headline -->\r\n");
      out.write("\t\t        \t");
}else{
      out.write("\r\n");
      out.write("\t\t        \t<div id=\"headline\"><br></div>\r\n");
      out.write("\r\n");
      out.write("\t\t        \t");
} 
      out.write("\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- ENDS slider holder -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- home-block -->\r\n");
      out.write("\t        \t\r\n");
      out.write("\t        \t\t        \t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- ENDS MAIN -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
