/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2014-01-19 13:50:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.base;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class creerBase_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- MAIN -->\r\n");
      out.write("<div id=\"main\">\t\r\n");
      out.write("\t<div class=\"wrapper clearfix\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h2 class=\"page-heading\"><span>Formulaire de creation de base de donnees</span></h2>\t\r\n");
      out.write("       \t<!-- <span>");
      out.print( request.getAttribute("title") );
      out.write("</span>-->\r\n");
      out.write("\t\t<!-- page content -->\r\n");
      out.write("       \t<div id=\"page-content\" class=\"clearfix\">\r\n");
      out.write("\t\t\t<form action=\"");
      out.print( request.getContextPath() );
      out.write("/base/valideBase\" method=\"post\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table align=\"center\" bgcolor=\"#99FFCC\" border=\"1\" width=\"70%\">\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td colspan=\"2\" align=\"center\">Creation de base de donnees </td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Nom de la base </td>\r\n");
      out.write("\t\t\t        <td><input type=\"text\" name=\"nomBase\" maxlength=\"25\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Nom de la table </td>\r\n");
      out.write("\t\t\t        <td><input type=\"text\" name=\"nomTable\" maxlength=\"40\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <br>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Nom du champ n1 </td>\r\n");
      out.write("\t\t\t        <td><input type=\"text\" name=\"champ1\" maxlength=\"10\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Valeur du champ n1 </td>\r\n");
      out.write("\t\t\t        <td><input type=\"text\" name=\"valeur1\" maxlength=\"10\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Type du champ n1 </td>\r\n");
      out.write("\t\t\t        <td><select name=\"typeChamp1\">\r\n");
      out.write("\t\t\t\t\t     <option value=\"varchar\" selected=\"selected\">Varchar</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"integer\" >integer</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"boolean\">boolean</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"dateTime\">Date Time</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t    </tr> \r\n");
      out.write("\t\t\t    <div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Nom du champ n2 </td>\r\n");
      out.write("\t\t\t        <td><input type=\"text\" name=\"champ2\" maxlength=\"10\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Valeur du champ n2 </td>\r\n");
      out.write("\t\t\t        <td><input type=\"text\" name=\"valeur2\" maxlength=\"10\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Type du champ n2 </td>\r\n");
      out.write("\t\t\t        <td><select name=\"typeChamp2\">\r\n");
      out.write("\t\t\t\t\t     <option value=\"varchar\" selected=\"selected\">Varchar</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"integer\" >integer</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"boolean\">boolean</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"dateTime\">Date Time</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t    </tr> \r\n");
      out.write("\t\t\t    <div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Nom du champ n3 </td>\r\n");
      out.write("\t\t\t        <td><input type=\"text\" name=\"champ3\" maxlength=\"10\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Valeur du champ n3 </td>\r\n");
      out.write("\t\t\t        <td><input type=\"text\" name=\"valeur3\" maxlength=\"10\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Type du champ n3 </td>\r\n");
      out.write("\t\t\t        <td><select name=\"typeChamp3\">\r\n");
      out.write("\t\t\t\t\t     <option value=\"varchar\" selected=\"selected\">Varchar</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"integer\" >integer</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"boolean\">boolean</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"dateTime\">Date Time</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t    </tr> \r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Nom de la table n2</td>\r\n");
      out.write("\t\t\t        <td><input type=\"text\" name=\"nomTable2\" maxlength=\"40\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <br>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Nom du champ n1 </td>\r\n");
      out.write("\t\t\t        <td><input type=\"text\" name=\"champ4\" maxlength=\"10\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Valeur du champ n1 </td>\r\n");
      out.write("\t\t\t        <td><input type=\"text\" name=\"valeur4\" maxlength=\"10\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Type du champ n1 </td>\r\n");
      out.write("\t\t\t        <td><select name=\"typeChamp4\">\r\n");
      out.write("\t\t\t\t\t     <option value=\"varchar\" selected=\"selected\">Varchar</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"integer\" >integer</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"boolean\">boolean</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"dateTime\">Date Time</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t    </tr> \r\n");
      out.write("\t\t\t    <div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Nom du champ n2 </td>\r\n");
      out.write("\t\t\t        <td><input type=\"text\" name=\"champ5\" maxlength=\"10\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Valeur du champ n5 </td>\r\n");
      out.write("\t\t\t        <td><input type=\"text\" name=\"valeur5\" maxlength=\"10\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Type du champ n2 </td>\r\n");
      out.write("\t\t\t        <td><select name=\"typeChamp5\">\r\n");
      out.write("\t\t\t\t\t     <option value=\"varchar\" selected=\"selected\">Varchar</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"integer\" >integer</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"boolean\">boolean</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"dateTime\">Date Time</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t    </tr> \r\n");
      out.write("\t\t\t    <div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Nom du champ n3 </td>\r\n");
      out.write("\t\t\t        <td><input type=\"text\" name=\"champ6\" maxlength=\"10\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Valeur du champ n6 </td>\r\n");
      out.write("\t\t\t        <td><input type=\"text\" name=\"valeur6\" maxlength=\"10\"></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td>Type du champ n3 </td>\r\n");
      out.write("\t\t\t        <td><select name=\"typeChamp6\">\r\n");
      out.write("\t\t\t\t\t     <option value=\"varchar\" selected=\"selected\">Varchar</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"integer\" >integer</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"boolean\">boolean</option>\r\n");
      out.write("\t\t\t\t\t     <option value=\"dateTime\">Date Time</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t    </tr> \r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <td colspan=\"2\" align=\"center\"><input type=\"submit\" value=\"Creer\"></td>\r\n");
      out.write("\t\t\t    </tr> \r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("        \t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t<!-- ENDS contact-sidebar -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\t        \t\r\n");
      out.write("       \t<!--  page content-->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ENDS MAIN -->\r\n");
      out.write("\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
