/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2014-01-23 18:34:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class layout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html class=\"no-js\">\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"utf-8\"/>\n");
      out.write("\t\t<title>Adopte un Chef</title>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t");
session.getAttribute("user"); 
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/style.css\"/>\n");
      out.write("\t\t<!--[if lt IE 9]>\n");
      out.write("\t\t\t<script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>\n");
      out.write("\t\t<![endif]-->\n");
      out.write("\t\t<link rel=\"stylesheet\" media=\"all\" href=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/style.css\"/>\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n");
      out.write("\t\t<!-- Adding \"maximum-scale=1\" fixes the Mobile Safari auto-zoom bug: http://filamentgroup.com/examples/iosScaleBug/ -->\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- JS -->\n");
      out.write("\t\t<script src=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/jquery-1.6.4.min.js\"></script>\n");
      out.write("\t\t<script src=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/css3-mediaqueries.js\"></script>\n");
      out.write("\t\t<script src=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/custom.js\"></script>\n");
      out.write("\t\t<script src=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/tabs.js\"></script>\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- Tweet -->\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/jquery.tweet.css\" media=\"all\"  /> \n");
      out.write("\t\t<script src=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/tweet/jquery.tweet.js\" ></script> \n");
      out.write("\t\t<!-- ENDS Tweet -->\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- superfish -->\n");
      out.write("\t\t<link rel=\"stylesheet\" media=\"screen\" href=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/superfish.css\" /> \n");
      out.write("\t\t<script  src=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/superfish-1.4.8/js/hoverIntent.js\"></script>\n");
      out.write("\t\t<script  src=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/superfish-1.4.8/js/superfish.js\"></script>\n");
      out.write("\t\t<script  src=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/superfish-1.4.8/js/supersubs.js\"></script>\n");
      out.write("\t\t<!-- ENDS superfish -->\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- prettyPhoto -->\n");
      out.write("\t\t<script  src=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/prettyPhoto/js/jquery.prettyPhoto.js\"></script>\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/prettyPhoto/css/prettyPhoto.css\"  media=\"screen\" />\n");
      out.write("\t\t<!-- ENDS prettyPhoto -->\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- poshytip -->\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/poshytip-1.1/src/tip-twitter/tip-twitter.css\"  />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/poshytip-1.1/src/tip-yellowsimple/tip-yellowsimple.css\"  />\n");
      out.write("\t\t<script  src=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/poshytip-1.1/src/jquery.poshytip.min.js\"></script>\n");
      out.write("\t\t<!-- ENDS poshytip -->\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- GOOGLE FONTS -->\n");
      out.write("\t\t<link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,300' rel='stylesheet' type='text/css'>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js\"></script>\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- Flex Slider -->\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/flexslider.css\" >\n");
      out.write("\t\t<script src=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/jquery.flexslider-min.js\"></script>\n");
      out.write("\t\t<!-- ENDS Flex Slider -->\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- Less framework -->\n");
      out.write("\t\t<link rel=\"stylesheet\" media=\"all\" href=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/lessframework.css\"/>\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- modernizr -->\n");
      out.write("\t\t<script src=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/modernizr.js\"></script>\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- SKIN -->\n");
      out.write("\t\t<link rel=\"stylesheet\" media=\"all\" href=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/skin.css\"/>\n");
      out.write("\t\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/global.css\" >\n");
      out.write("\t\t\n");
      out.write("\t\t<script  src=\"");
      out.print( request.getContextPath() );
      out.write("/res/js/js_pack.js\"></script>\n");
      out.write("\t</head>\n");
      out.write("\n");
      out.write("\t<body lang=\"fr\">\n");
      out.write("\t\t<header class=\"clearfix\">\n");
      out.write("\t\t<!-- top widget -->\n");
      out.write("\t\t\t<div id=\"top-widget-holder\">\n");
      out.write("\t\t\t\t<div class=\"wrapper\">\n");
      out.write("\t\t\t\t\t<div id=\"top-widget\">\n");
      out.write("\t\t\t\t\t\t<div class=\"padding\">\n");
      out.write("\t\t\t\t\t\t\t<ul  class=\"widget-cols clearfix\">\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"first-col\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"widget-block\">\n");
      out.write("\t\t\t                         \t<img src=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/img/heart/O1.jpg\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"second-col\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"widget-block\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"third-col\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"widget-block\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"fourth-col\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"widget-block\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\t\n");
      out.write("\t\t\t\t\t\t\t</ul>\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<a href=\"#\" id=\"top-open\">Menu</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- ENDS top-widget -->\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div class=\"wrapper clearfix\">\n");
      out.write("\t\t\t\t<a href=\"");
      out.print( request.getContextPath() );
      out.write("\" id=\"logo\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/img/logo_auc.png\" alt=\"Zeni\"></a>\t\n");
      out.write("\t\t\t\t<nav>\n");
      out.write("\t\t\t\t\t<ul id=\"nav\" class=\"sf-menu\">\n");
      out.write("\t\t\t\t\t\t<li class=\"current-menu-item\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("\">ACCUEIL</a></li>\n");
      out.write("\t\t\t\t\t\t");
if (session.getAttribute("user") != null)	 { 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/profil?user=");
 out.println(session.getAttribute("idUser"));
      out.write("\">VOTRE PROFIL</a></li>\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/base/voirBase\">VOIR VOS BASES</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/base/modifierBase\">MODIFIER VOS BASE</a>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/base/creerBase\">CREER VOTRE BASE</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/base/ajouterTable\">AJOUTER UNE TABLE</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/base/ajouterChamps\">AJOUTER DES CHAMPS</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/base/saisieXPATH\">XPATH</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">CONVERTION DES BASES</a>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"\">CONVERTIR BASE EN XML</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"\">CONVERTIR XML EN TXT</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t                ");
if (session.getAttribute("user")!=null) {
      out.write("\n");
      out.write("\t\t               \t<li ><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/deconnection\" class=\"hover_pink\">DECONNEXION </a> <!-- redirection vers page inscription --></li>\n");
      out.write("\t\t                ");
} 
      out.write("\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<div id=\"combo-holder\"></div>\n");
      out.write("\t\t\t\t</nav>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</header>\n");
      out.write("\t  \n");
      out.write("\t\t<div id=\"context\">\n");
      out.write("\t\t\t");
 
			 out.flush();
			 String url = request
					 .getRequestURI()
					 .substring(request.getContextPath().length()+1);
			 
			 if( url.isEmpty() ) {
				url = "index";
			 }
			 
			 request.getRequestDispatcher("/WEB-INF/views/"+url+".jsp")
			 .include(request, response);
			
			 
			
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t  \n");
      out.write("\t  \t<footer>\n");
      out.write("\t\t\t<div class=\"wrapper\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<ul  class=\"widget-cols clearfix\">\n");
      out.write("\t\t\t\t\t<li class=\"first-col\">\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-block\">\n");
      out.write("\t\t\t\t\t\t\t<h4>NOS PACKS</h4>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("                                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/pack/packNoTime\">NO TIME</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/pack/packJunior\">JUNIOR</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/pack/packExpert\">EXPERT</a></li>\n");
      out.write("                                \n");
      out.write("                            </ul>\n");
      out.write("                            <br>\n");
      out.write("                            <h4>NOS PACKS CLASSIQUE</h4>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("                                 <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/pack/packAmoureux\">DINER EN AMOUREUX</a></li>\n");
      out.write("                                 <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/pack/packNoel\">NOEL PRESTIGE</a></li>\n");
      out.write("                                 <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/pack/packAnniversaire\">ANNIVESAIRE</a></li>\n");
      out.write("                                 \n");
      out.write("                             </ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<li class=\"second-col\">\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-block\">\n");
      out.write("\t\t\t\t\t\t\t<h4>MENU</h4>\n");
      out.write("                             <ul>\n");
      out.write("                                 <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("\">ACCUEIL</a></li>\n");
      out.write("                                 <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/listeChef\">NOS CHEFS</a></li>\n");
      out.write("                                 <li><a href=\"\">PLUS ENCORE</a></li>\n");
      out.write("                                 <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/about/about\">ABOUT</a></li>\n");
      out.write("                                 <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/about/contact\">CONTACT</a></li>\n");
      out.write("                             </ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<li class=\"third-col\">\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-block\">\n");
      out.write("\t         \t\t\t\t<h4>AUTRES</h4>\n");
      out.write("                            <ul>\n");
      out.write("                      \t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/about/faq\">FAQ</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/devenirChef\">DEVENIR CHEF</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/devenirClient\">DEVENIR CLIENT</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/about/mentionsLegales\">MENTION LEGALE</a></li>\n");
      out.write("                                <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/about/planSite\">PLAN DU SITE</a></li>\n");
      out.write("                            </ul>\n");
      out.write("\t\t         \t\t</div>\n");
      out.write("\t\t         \t</li>\n");
      out.write("\t\t         \t\t\n");
      out.write("\t\t\t\t\t<li class=\"fourth-col\">\n");
      out.write("\t\t\t\t\t\t<div class=\"widget-block\">\n");
      out.write("\t\t\t\t\t\t\t<h4>RECETTES</h4>\n");
      out.write("                            <ul>\n");
      out.write("                                <li><a href=\"\">PLATS DU MONDE</a></li>\n");
      out.write("                                <li><a href=\"\">PLAT DE NOS REGIONS</a></li>\n");
      out.write("                                <li><a href=\"page.html\">DESSERTS</a></li>\n");
      out.write("                                <li><a href=\"page.html\">CUISINE FACILE</a></li>\n");
      out.write("                                <li></li>\n");
      out.write("                            </ul>\n");
      out.write("                   \t\t</div>\n");
      out.write("\t\t\t\t\t</li>\t\n");
      out.write("\t\t\t\t</ul>\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"footer-bottom\">\n");
      out.write("\t\t\t\t\t<div class=\"left\">Design by <a href=\"#\" > adopteunchef.com</a></div>\n");
      out.write("\t\t\t\t\t<div class=\"right\">\n");
      out.write("\t\t\t\t\t\t<ul id=\"social-bar\">\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\"  title=\"Become a fan\" class=\"poshytip\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/img/social/facebook.png\"  alt=\"Facebook\" /></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\" title=\"Follow my tweets\" class=\"poshytip\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/img/social/twitter.png\"  alt=\"twitter\" /></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\"  title=\"Add to the circle\" class=\"poshytip\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/res/styles/default/img/social/plus.png\" alt=\"Google plus\" /></a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</footer>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t</body>\n");
      out.write("\t\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
